# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit configuration for TouchBarFix
# This file configures AI code review settings for the repository

# Review settings
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_empty_files: true
  
# Language-specific settings  
language:
  swift:
    level: "standard"
  shell:
    level: "standard"

# File patterns to review
path_filters:
  - "**/*.swift"
  - "**/*.sh" 
  - "**/Info.plist"
  - "**/Package.swift"
  - "**/*.md"

# Ignore patterns
path_ignore:
  - ".build/**"
  - "node_modules/**"
  - "*.dmg"
  - "*.app/**"
  - ".git/**"