# CodeRabbit Configuration
# https://docs.coderabbit.ai/getting-started/configure-coderabbit

language: en

reviews:
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "App/Sources/**/*.swift"
      instructions: "Review for Swift best practices, memory management, and macOS API usage"
    - path: "App/Tests/**/*.swift"
      instructions: "Ensure tests are isolated, use proper mocking, and cover edge cases"

knowledge_base:
  linear:
    team_keys:
      - TOU
